# Generated by Django 4.2.2 on 2023-06-24 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0002_remove_book_pages_page_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="page_set",
                to="management.book",
            ),
        ),
    ]
